# HTS [Part 3]

In [1]:
%pylab inline
import sys
from ipywidgets import interact

Populating the interactive namespace from numpy and matplotlib


//anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [2]:
sys.path.append('src')
from motorControl import *
from trajectoryPlanning import *
from util import *

## Load Absolute Home, Upper right corner, out of the way, aligned with sharpie marks
f = open('savedPositions/absolute/home.p', 'r')
home = pickle.load(f)
f.close()

In [3]:
rc = connect(portName = "/dev/tty.usbserial-A9ETDN3N")
rc.Open()

1

### Initialized Motor Classes

- Really important to initialze these first to restore positions from last session!

In [4]:
#Initialize motor objects for each motor:
vL = Motor(address = 0x81, motorNumber = 2, rc = rc, signFlipped = True, \
           motorCounter = 0, kPID = [1e-2, 1.0])
vR = Motor(address = 0x81, motorNumber = 1, rc = rc, signFlipped = True, \
           motorCounter = 1, kPID = [1e-2, 1.0])
LR = Motor(address = 0x80, motorNumber = 1, rc = rc, signFlipped = True, 
           motorCounter = 2, kPID = [1e-2, 1.0])
FB = Motor(address = 0x80, motorNumber = 2, rc = rc, signFlipped = False, \
           motorCounter = 3, kPID = [1e-2, 1.0])
yaw = Motor(address = 0x82, motorNumber = 2, rc = rc, signFlipped = True, \
            motorCounter = 4, kPID = [1e-2, 1.0])
pitch = Motor(address = 0x82, motorNumber = 1, rc = rc, signFlipped = True, \
              motorCounter = 5, kPID = [1e-2, 1.0])

#Keep in a nice motor list:
motors = [vL, vR, LR, FB, yaw, pitch]

In [5]:
getPositions(motors)

[-36657, 37693, -775, -10468, -4824, -4271]

In [6]:
home

[-1047, -2826, 0, 0, 0, -2]

In [43]:
MC = ManualControl(rc)

interact(MC.manualControl, leftUD = (-50, 50), rightUD = (-50, 50), leftRight = (-127, 127), \
         fB = (-127, 127), tilt = (-50, 50), pan = (-50, 50))

<function ipywidgets.widgets.interaction.<lambda>>

In [44]:
stopAll(rc)
savePositions(motors)
getPositions(motors)

[-88030, 84024, -103437, -10468, -17547, -16290]

In [33]:
stopAll(rc)
savePositions(motors)
getPositions(motors)

[-88030, 84024, -11178, -10468, 9235, -16290]

In [9]:
# levelRig(motors, home, rc, moveTime = 5.0)

Rig is not level!, difference from home = -6055
Rig Leveled! Difference from home = -7247


## Save absolute home

- Only needed for hard resets

In [26]:
# #Upper right corner, out of the way, aligned with sharpie marks
# f = open('savedPositions/absolute/home.p', 'wb')
# pickle.dump(getPositions(motors), f, protocol=pickle.HIGHEST_PROTOCOL)
# f.close()

## Save Relative Position

In [45]:
# delta = np.array(getPositions(motors))-np.array(home)
# f = open('savedPositions/relative/HTS2/P.p', 'wb')
# pickle.dump(delta, f, protocol=pickle.HIGHEST_PROTOCOL)
# f.close()

## Load Relative Positions

In [46]:
#Position A
f = open('savedPositions/relative/HTS2/A.p', 'r')
A = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position B
f = open('savedPositions/relative/HTS2/B.p', 'r')
B = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position C
f = open('savedPositions/relative/HTS2/C.p', 'r')
C = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position D
f = open('savedPositions/relative/HTS2/D.p', 'r')
D = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position E
f = open('savedPositions/relative/HTS2/E.p', 'r')
E = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position F
f = open('savedPositions/relative/HTS2/F.p', 'r')
F = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position G
f = open('savedPositions/relative/HTS2/G.p', 'r')
G = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position C960
f = open('savedPositions/relative/HTS2/C960.p', 'r')
C960 = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position H
f = open('savedPositions/relative/HTS2/H.p', 'r')
H = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position I
f = open('savedPositions/relative/HTS2/I.p', 'r')
I = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position J
f = open('savedPositions/relative/HTS2/J.p', 'r')
J = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position K
f = open('savedPositions/relative/HTS2/K.p', 'r')
K = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position L
f = open('savedPositions/relative/HTS2/L.p', 'r')
L = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position M
f = open('savedPositions/relative/HTS2/M.p', 'r')
M = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position N
f = open('savedPositions/relative/HTS2/N.p', 'r')
N = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position O
f = open('savedPositions/relative/HTS2/O.p', 'r')
O = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

#Position P
f = open('savedPositions/relative/HTS2/P.p', 'r')
P = pickle.load(f)+np.array(home) #Return to absolute coords
f.close()

## Move the rig

In [51]:
targetPositions = O
totalTime = 45.0
rampTime = 5.0

startingPositions = getPositions(motors)
lookAheadTime = 1.0
tolerance = 100.0 #Anything less than this many ticks we're calling "Not a move"

motorsToMove = []
targetPositionsToMove = []
for i, motor in enumerate(motors):
    if abs(motor.getPosition()-targetPositions[i]) > tolerance:
        motorsToMove.append(motor)
        targetPositionsToMove.append(targetPositions[i])
        
trajectories = []
for i, motor in enumerate(motorsToMove):
    trajectories.append(SimpleQuadraticTrajectory(tu = rampTime, tt = totalTime, \
                                            p1 = motor.getPosition(), p2 = targetPositionsToMove[i]))
    
print np.array(targetPositions) - startingPositions
print 'Planning to move ' +  str(len(motorsToMove)) + ' motors.'

[    0     0 92067     0 26738     0]
Planning to move 2 motors.


In [52]:
for motor in motorsToMove:
    motor.initialize(targetVelocityMin = -25000.0, targetVelocityMax = 25000.0)
    motor.clearTracking()
    
startTime = time.time()
timeElapsed = 0.0
    
while timeElapsed < totalTime:
    timeElapsed = time.time()-startTime
    
    for i, motor in enumerate(motorsToMove):
        lookAheadValue = trajectories[i].compute(timeElapsed + lookAheadTime)
        motor.controlledMove(targetPosition = lookAheadValue, timeToReach = lookAheadTime)

stopAll(rc)
savePositions(motors)
print getPositions(motors), targetPositions
print getPositions(motors) - np.array(targetPositions)

voltage too low on motor 2
excess voltage on motor 2
excess voltage on motor 2
excess voltage on motor 2
[-88030, 84024, -11354, -10468, 9166, -16290] [-88030  84024 -11178 -10468   9235 -16290]
[   0    0 -176    0  -69    0]


In [30]:
stopAll(rc)
savePositions(motors)

In [31]:
A

array([ -2964,  -2454, -33986,  -3689, -64656,  19806])

In [33]:
getPositions(motors)

[-2967, -2447, -33925, -3705, -64575, 19770]